"""empty message

Revision ID: 301ef41b4de1
Revises: 4652ddf8f87a
Create Date: 2023-07-17 22:13:27.760715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301ef41b4de1'
down_revision = '4652ddf8f87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_db', sa.DATETIME(), nullable=False))
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
